table 'Fait parc_immobilier'
	lineageTag: 48a01722-5e81-4267-ae44-bee68db702f9

	column date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 175191ee-0741-4070-84e2-658e0d81e1c0
		summarizeBy: none
		sourceColumn: date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column n_logements_vacants
		dataType: int64
		formatString: 0
		lineageTag: a62bb3a7-7c9b-498f-8ca5-2b4cc05463f1
		summarizeBy: none
		sourceColumn: n_logements_vacants

		annotation SummarizationSetBy = User

	column n_logements
		dataType: int64
		formatString: 0
		lineageTag: fc86ec81-076e-4e0d-ab36-396b1f8605ba
		summarizeBy: sum
		sourceColumn: n_logements

		annotation SummarizationSetBy = Automatic

	column 'Code INSEE'
		dataType: string
		lineageTag: 30e8eb57-bba3-4371-8308-4cacf7230733
		summarizeBy: none
		sourceColumn: Code INSEE

		annotation SummarizationSetBy = Automatic

	partition 'Fait parc_immobilier' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\sebas\Downloads\archive (5)\parc_immobilier.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Promu = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Txt = Table.TransformColumnTypes(Promu, {{"departement", type text},{"id_ville", type text},{"date", Int64.Type},{"n_logements", Int64.Type},{"n_logements_vacants", Int64.Type}}),
				    Code = Table.AddColumn(Txt, "Code INSEE", each Text.Start(Text.PadStart([departement],2,"0"),2) & Text.PadStart([id_ville],3,"0"), type text),
				    DateAnnee = Table.TransformColumns(Code, {{"date", each if _ = null then null else #date(_,1,1), type date}}),
				    Nettoyage = Table.RemoveColumns(DateAnnee, {"departement","ville","id_ville"}),
				    Valides = Table.SelectRows(Nettoyage, each [Code INSEE] <> null and [date] <> null)
				in
				    Valides

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

